### ISSUE TITLE
Module not found: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by muhaimincs** [colbyfayock/use-custom-hook#13]
Has it ever occurred to you while running `yarn develop`. 

yarn version: 2.3.3

**Comment by colbyfayock** [comment]
i confirmed i was able to reproduce this issue on yarn v2.3.3, this was the first time i used yarn 2

confirmed it's still working on yarn v1.22.0 though

**Comment by muhaimincs** [comment]
so you completely have no idea the existence of `.pnp.js` file and `.yarnrc` file

**Comment by colbyfayock** [comment]
not familiar, though generally i understand what `rc` files typically mean. feel free to submit a PR for adding for v1.22.0 if youd like
